<pre>--- Summary ---
Tests passed: 0 out of 1

--- Details ---
Test #0: failed 
Test case description: ML4T-220
Traceback:
  File "grade_strategy_learner.py", line 237, in test_strategy
    ) = run_with_timeout(timeoutwrapper_strategylearner, max_time, (), {})
  File "grading.py", line 167, in run_with_timeout
    raise TimeoutException("Exceeded time limit!")
TimeoutException: Exceeded time limit!

</pre>
